# -*- coding: utf-8 -*-
"""Piadocas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjZb2OhjfPfTRXfDQbOdcaxzQNvoFLDW
"""

Nota1 = 5.8
Nota2 = 9.3
Media = (Nota1 + Nota2) / 2
print(Media)

Num1 = 10
Num2 = 5
Soma = Num1 + Num2
print("O resultado é:",Soma)

Base = 7
Altura = 5
Area = (Base * Altura) / 2
AreaTotal = Area * 6
print(AreaTotal)

r = 6
pi = 3.14
altura= 4
Area = (pi+altura) * (r ** 2)
print(Area)

Temperatura = 10
Fahrenheit = (Temperatura * 1.8 ) + 32
print(Fahrenheit)

try:
  print(x)
except:
  print("An exception occurred")

x ="ola"
try:
  print(x)
except:
  print("An exception occurred")

lista01 = [1,4,5,6]
print(lista01)

lista02 = [1,3,4.5,"ola"]
print(lista02)
print(lista02[1])
print(lista02[1:3])
print(lista02[-1])

lista03 = [1,2,3,5,5]
lista03[3]= 4
print(lista03)

lista04 = [1,5,3,5,5]
print(lista04)

lista05 = [[1,3],[4,6]]
print(lista05)

lista06 = [1,2,3,4,6,"erro"]
lista06.append(7)
lista06.insert(4,5)
lista06.remove("erro")
print(lista06)

lista07 = [1,2,3,4,5]
print(len(lista07))

tupla01 =(1,2,3.5,"ola")
print(tupla01)

tupla02 = (1,2,3,4,5)
tupla02[3] = 6
print(tupla02)

lista08 = [1,2,3,4,5]
tupla03 = tuple(lista08)
print(tupla03)

tupla04 = ('a','b','c','d')
lista09 = list(tupla04)
print(lista09)

set01 = {1,2.6,3,4,5,'ola',3.5}
print(set01)

set02 = {1,2,3,4,5}
set02.add(6)
set02.remove(3)
print(set02)

set03 = {1,2,3,4,5}
set04 = {4,5,6,7,8}
set05 = set03.union(set04)
print(set05)

dic01 = {1:"ola",2:"mundo", "tenha":"um bom dia"}
print(dic01)
print(dic01[1])
print(dic01["tenha"])

dic02 = {1:1,2:4,3:9,4:16}
print(dic02)
#adicionar
dic02[5] = 25
print(dic02)
#remover
del dic02[2]
print(dic02)
#alterar
dic02[1] = 0
print(dic02)